name: api-wp

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest


    env:
      WEBHOOK_VERIFY_TOKEN: ${{ secrets.WEBHOOK_VERIFY_TOKEN ))
      GRAPH_API_TOKEN: ${{ secrets.GRAPH_API_TOKEN ))

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: intall dependencies
        run: pip install -r requirements.txt
        
      
      - name: Run Proyect
        run: python main.py
